# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Henry and Dreams🔴🔵
subtitle: "There are good days and there are bad days"
description: ""
keywords:
author: Henry Wu
language: en
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://sweet2honey.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: false
  auto_detect: false
  tab_replace: ""
  wrap: false
  hljs: true
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""
marked:
  prependRoot: true
  postAsset: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 5
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  "machine learning": machine-learning
  "deep learning": deep-learning
  "game developing": game-developing
tag_map:
  "c++": cpp
  "C++": cpp

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
# include:
# exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: maupassant
# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
# deploy:
#   type: "git"
#   repo: https://github.com/sweet2honey/sweet2honey.github.io
#   branch: gh-pages

# Hexo-all-minifier
all_minifier: false

# hexo markdown支持数学公式插件
# mathjax:
#   tags: none # or 'ams' or 'all'
#   single_dollars: true # enable single dollar signs as in-line math delimiters
#   cjk_width: 0.9 # relative CJK char width
#   normal_width: 0.6 # relative normal (monospace) width
#   append_css: true # add CSS to pages rendered by MathJax
#   every_page: false # if true, every page will be rendered by MathJax regardless the `mathjax` setting in Front-matter
#   packages: # extra packages to load
#   extension_options: {}
#     # you can put your extension options here
#     # see http://docs.mathjax.org/en/latest/options/input/tex.html#tex-extension-options for more detail

feed:
  content_limit: 50
  content_limit_delim: '。'

markdown_it_plus:
  plugins:
    - plugin:
        name: '@iktakahiro/markdown-it-katex'
        enable: true
        options:
          strict: false
